### ISSUE TITLE
example code

### ISSUE THREAD

**Issue by loupus** [rick-de-water/Lingo#58]
Hello,
Can you please add some example code for how to use  lingo::string_converter

**Comment by rick-de-water** [comment]
Its been a while since I worked on this, and a while since I did anything C++, so I had to do some reading on what I did. It's weird to read your own code and it feeling like someone else wrote it 😅

As I recall, `string_converter` is at the core of the conversions between encodings; it is the object that does all the actual work. It is intended to be fairly simple to use. You first define a converter by choosing your source and destination pages and encodings. So for example, if you want to convert ASCII to UTF16, you create a `string_converter` like this:

```c++
auto converter = lingo::string_converter<
    lingo::encoding::none<char, char>,          // source encoding
    lingo::page::ascii,                         // source code page
    lingo::encoding::utf16<char16_t, char32_t>, // destination encoding
    lingo::page::unicode                        // destination code page
>();
```

Then, you can use the `converter.convert` methods to convert your strings. There are several overloads, some just taking a `lingo::string_view` and returning the resulting `lingo::string`, but also low level ones that take source and destination buffers for the least amount of memory allocations.

If you have more specific questions, I will try my best to answer them.

**Comment by loupus** [comment]
Thank you,
I couldnt do it, here is my sample code 

```
#include <iostream>
#include <iomanip>
#include "lingo/string.hpp"

void tryme()
{

auto sc = lingo::string_converter<
        lingo::encoding::none<char, char>
        ,lingo::page::iso_8859_9
        ,lingo::encoding::utf8<uint8_t, char32_t>
        , lingo::page::unicode>();
std::string trstr{"\xDC,\xDD,\xDE,\xE7,\xFC,\xFD,\xFE,\xD0,\xF0"}; // ÜİŞçışĞğ   iso_8859_9

lingo::basic_string_view<
    lingo::encoding::none<char,char>
    ,lingo::page::iso_8859_9> lsvtr{trstr.c_str()};

 auto d =  sc.convert<uint8_t>(lsvtr);

  if(d.length() > 0)
  {    
          for(auto& aba : d)
          {
                  std::cout << "dest : " << std::setw(2) << std::hex << aba << std::endl;
          }		
  }
}

int main()
{
    std::cout << "hayde bakemmm" << std::endl;
    tryme();
    return 0;
}
```

**Comment by rick-de-water** [comment]
I managed to get your code to work. The first issue is that you were using `char` instead of `unsigned char` as units, the second issue was that convert is a low level function and requires an allocator. The following code works:
```c++
#include <iostream>
#include <iomanip>
#include <lingo/string.hpp>

#include <memory>

void tryme()
{
    auto sc = lingo::string_converter<
        lingo::encoding::none<unsigned char, unsigned char>,
        lingo::page::iso_8859_9,
        lingo::encoding::utf8<uint8_t, char32_t>,
        lingo::page::unicode>();

    std::string trstr{ "\xDC,\xDD,\xDE,\xE7,\xFC,\xFD,\xFE,\xD0,\xF0" }; // ÜİŞçışĞğ   iso_8859_9

    auto lsvtr = lingo::basic_string_view<
        lingo::encoding::none<unsigned char, unsigned char>,
        lingo::page::iso_8859_9>((unsigned char*)trstr.c_str());

    auto d = sc.convert(lsvtr, std::allocator<uint8_t>());

    if (d.length() > 0)
    {
        for (auto& aba : d)
        {
            std::cout << "dest : " << std::setw(2) << std::hex << aba << std::endl;
        }
    }
}

int main()
{
    std::cout << "hayde bakemmm" << std::endl;
    tryme();
    return 0;
}
```

However, there are easier ways to do the conversion. You can simply pass your encoded `string_view` to the constructor of a string with the encoding that you want, and it will automatically do the conversion:

```c++
#include <iostream>
#include <iomanip>
#include <lingo/string.hpp>

void tryme()
{
    std::string trstr{ "\xDC,\xDD,\xDE,\xE7,\xFC,\xFD,\xFE,\xD0,\xF0" }; // ÜİŞçışĞğ   iso_8859_9

    auto lsvtr = lingo::basic_string_view<
        lingo::encoding::none<unsigned char, unsigned char>,
        lingo::page::iso_8859_9>((unsigned char*)trstr.c_str());

    auto d = lingo::utf8_string(lsvtr); // Just turn it into utf8, thank you!

    if (d.length() > 0)
    {
        for (auto& aba : d)
        {
            std::cout << "dest : " << std::setw(2) << std::hex << aba << std::endl;
        }
    }
}

int main()
{
    std::cout << "hayde bakemmm" << std::endl;
    tryme();
    return 0;
}
```

**Comment by loupus** [comment]
Tank you very much, it was very helpful

28 May 2024 Sal 21:21 tarihinde Rick de Water ***@***.***>
şunu yazdı:
